### ISSUE TITLE
部署完成后无法进入系统

### ISSUE THREAD

**Issue by isen121** [dqzboy/chatgpt-web#1]
### 前置确认

- [X] 我确认我的网络可以访问openai，使用的是最新脚本，并且服务器规格 > 1C1G

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

CentOS 7

### 问题描述 😯

一键部署完成后，访问端口出现
![image](https://github.com/dqzboy/ChatGPT/assets/134914963/e40b2512-c803-455f-8bcc-6067a48b16d0)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by dqzboy** [comment]
参考README配置下Nginx；https://github.com/dqzboy/ChatGPT/blob/main/ChatGPT-Web-Admin/README.md

**Comment by isen121** [comment]
根据nginx编写了配置还是出现相同问题
![image](https://github.com/dqzboy/ChatGPT/assets/134914963/79f8a561-3da5-451d-9629-01d234906534)
![image](https://github.com/dqzboy/ChatGPT/assets/134914963/7ab0c55f-acb6-488d-8fff-bd4e41b52012)

**Comment by dqzboy** [comment]
添加配置之后，重新加载nginx没

**Comment by isen121** [comment]
重新加载了还是不行
![image](https://github.com/dqzboy/ChatGPT/assets/134914963/1c9ed5f3-a66e-49e3-bb2b-b0a1ae543f10)

**Comment by dqzboy** [comment]
你是改的哪个配置文件？是这个吗 /etc/nginx/conf.d/default.conf

**Comment by isen121** [comment]
我使用的宝塔软件商店安装的nginx然后点击设置里有配置文件的更改，在/etc/nginx/conf.d/default.conf里面没有文件
![image](https://github.com/dqzboy/ChatGPT/assets/134914963/aaa30b4f-7882-41a1-9e18-aec3675673c9)

**Comment by dqzboy** [comment]
![image](https://github.com/dqzboy/ChatGPT/assets/42825450/65f32792-2783-4422-abf2-215aea79bd4c)
这个文件里面看下 你加在这个里面的吗？

**Comment by isen121** [comment]
是的，在这个文件
![image](https://github.com/dqzboy/ChatGPT/assets/134914963/8ab508f4-4cd1-4f2b-9637-1336540a85b1)

**Comment by dqzboy** [comment]
nginx -t检查配置是否正确；检查下后端 3002端口是否监听

**Comment by isen121** [comment]
是这个吗
![image](https://github.com/dqzboy/ChatGPT/assets/134914963/cf64c556-c599-4f5f-a8b1-3fc139297f33)

**Comment by dqzboy** [comment]
没问题哦，那就还是代理后端的nginx配置没有配置对

**Comment by isen121** [comment]
好的，谢谢，我再重新运行配置试试，麻烦了
