### ISSUE TITLE
Kerwin1202_env.example 配置

### ISSUE THREAD

**Issue by krxiaoyu** [dqzboy/chatgpt-web#2]
### 前置确认

- [X] 我确认我的网络可以访问openai，使用的是最新脚本，并且服务器规格 > 1C1G

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

CentOS 7

### 复现步骤 🕹

Kerwin1202/chatgpt-web

### 问题描述 😯

大佬好，我准备搭建Kerwin1202/chatgpt-web， 但是env.example 不知要改哪几个参数，我在这一块是小白，可以告诉我需要改哪几个参数吗？ 如果有示例最好了

### 终端日志 📒

```log
<此处粘贴终端日志>
Kerwin1202/chatgpt-web
```

**Comment by dqzboy** [comment]
配置下AUTH_SECRET_KEY= 、ROOT_USER=、 MONGODB_URL=mongodb://chatgpt:xxxx@yourip:port  其他的可以部署完成之后在WEB端进行配置

**Comment by krxiaoyu** [comment]
![image](https://github.com/dqzboy/ChatGPT/assets/30654763/cc734294-46d9-45ed-81d5-985b376f55e0)
卡死在这个位置，编译了半个小时都没有通过，知道是什么原因吗？ 是不是软件版本用的不对？

**Comment by dqzboy** [comment]
服务器几G内存？

**Comment by krxiaoyu** [comment]
服务器1G内存

**Comment by dqzboy** [comment]
那编译过不去，内存太低了

**Comment by krxiaoyu** [comment]
最低要求多少G？ 或者有其他办法没？

**Comment by dqzboy** [comment]
2G；或者你自己PC机搞个大内存的虚拟机，然后把编译好的包拷贝到你的服务器上也是可以的

**Comment by krxiaoyu** [comment]
好的，那我研究一下试试

**Comment by krxiaoyu** [comment]
搞定了，感谢大佬的支持
