### ISSUE TITLE
前、后端构建均失败。

### ISSUE THREAD

**Issue by Facebooksx** [dqzboy/chatgpt-web#4]
### 前置确认

- [X] 我确认我的网络可以访问openai，使用的是最新脚本，并且服务器规格 > 1C1G

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

-------------------------------------<提 示>-------------------------------------
                           开始进行构建.构建快慢取决于你的环境
-------------------------------------< END >-------------------------------------

-----------------------------------<前端构建>-----------------------------------
《前端构建中，请稍等...》
Killed
 ELIFECYCLE  Command failed with exit code 137.
 ELIFECYCLE  Command failed.
ERROR: "type-check" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
-------------------------------------< END >-------------------------------------

------------------------------------<后端构建>-----------------------------------
《后端构建中，请稍等...》
ESM⚡️ Build success in 264ms
-------------------------------------< END >-------------------------------------

-----------------------------------<后端部署>-----------------------------------
Service Copy Success
后端程序未运行,启动中...
cp: cannot stat '/data/chatgpt-web/chatgpt-web/dist/*': No such file or directory
Copy Error

### 问题描述 😯

-------------------------------------<提 示>-------------------------------------
                           开始进行构建.构建快慢取决于你的环境
-------------------------------------< END >-------------------------------------

-----------------------------------<前端构建>-----------------------------------
《前端构建中，请稍等...》
Killed
 ELIFECYCLE  Command failed with exit code 137.
 ELIFECYCLE  Command failed.
ERROR: "type-check" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
-------------------------------------< END >-------------------------------------

------------------------------------<后端构建>-----------------------------------
《后端构建中，请稍等...》
ESM⚡️ Build success in 264ms
-------------------------------------< END >-------------------------------------

-----------------------------------<后端部署>-----------------------------------
Service Copy Success
后端程序未运行,启动中...
cp: cannot stat '/data/chatgpt-web/chatgpt-web/dist/*': No such file or directory
Copy Error

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by dqzboy** [comment]
内存不够，前端构建不成功

**Comment by Facebooksx** [comment]
谢谢，追问一个问题，ChatGPT-WEB、ChatGPT-WEB-Admin、ChatGPT-Next-WEB，这三种方案哪种可以使用accesstoken？

**Comment by dqzboy** [comment]
ChatGPT-Next-WEB这个不支持，用ChatGPT-WEB-Admin脚本就行
